### ISSUE TITLE
template from adobe premiere not working with recentering.

### ISSUE THREAD

**Issue by fjoralbmuca** [pyahmed/sub2xml#2]
thanks for this script. I am having two issues. One i dont know how to add the gSizeX and y to my exported template from premiere. Second when I add two lines, I get one line with /N

**Comment by pyahmed** [comment]
I haven't used this script since long time. If you have the option use the latest Premiere CC, which has real support for subtitles. What exactly does gSizeX/Y do?

**Comment by fjoralbmuca** [comment]
solved by puting text on a text box and removed all the possitioning
